# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "hls-pynq"
BBFILE_PATTERN_hls-pynq = "^${LAYERDIR}/"
BBFILE_PRIORITY_hls-pynq = "10"

# Depends on poky core and the jupyter layer (already in the EDF manifest)
LAYERDEPENDS_hls-pynq = "core jupyter-layer"
LAYERSERIES_COMPAT_hls-pynq = "scarthgap"
