# Add the Jupyter Lab server (packages from meta-jupyter) and the autostart
# service to the EDF disk image.
IMAGE_INSTALL:append = " packagegroup-python3-jupyter jupyter-startup"

# Bake a root password into the rootfs so the board is reachable over
# serial/ssh right after flashing, with no interactive setup. The hash is
# generated by the Makefile 'root-password' stage into root-password.inc:
#   LINUX_EDF_PASSWORD=... make build-linux
# 'include' is soft on purpose: a plain 'bitbake' without the make stage still
# parses (just with no preset password) instead of erroring out.
include ${THISDIR}/root-password.inc

# Stage 2 (the pynq library) will append here, e.g.:
#   IMAGE_INSTALL:append = " python3-pynq python3-pynq-notebooks"
