# Add the Jupyter Lab server (packages from meta-jupyter) and the autostart
# service to the EDF disk image.
IMAGE_INSTALL:append = " packagegroup-python3-jupyter jupyter-startup"

# Enable systemd-resolved mDNS so the board is discoverable as <hostname>.local
# (e.g. amd-edf.local) with no per-boot 'resolvectl mdns end0 yes'.
IMAGE_INSTALL:append = " mdns-config"

# Permit password-based root SSH login (debug-tweaks is off, so OpenSSH would
# otherwise reject the baked-in root password). Lets you scp a new boot.bin to
# the board instead of pulling the SD card.
IMAGE_INSTALL:append = " ssh-permit-root"

# PYNQ Python runtime dependencies (from python-pynq.inc) plus matplotlib.
IMAGE_INSTALL:append = " packagegroup-pynq-python"

# Bake a root password into the rootfs so the board is reachable over
# serial/ssh right after flashing, with no interactive setup. The hash is
# generated by the Makefile 'root-password' stage into root-password.inc:
#   LINUX_EDF_PASSWORD=... make build-linux
# 'include' is soft on purpose: a plain 'bitbake' without the make stage still
# parses (just with no preset password) instead of erroring out.
include ${THISDIR}/root-password.inc

# Stage 2: the pynq library itself (Overlay/allocate/MMIO). Pulls in
# python3-pynqmetadata / python3-pynqutils and the libcma allocator.
# Build the recipes standalone first to validate them:
#   MACHINE=amd-cortexa9thf-neon-common bitbake python3-pynq
# Note: no python3-pynq-notebooks -- PYNQ 3.x ships example notebooks inside the
# package (site-packages/pynq/notebooks) and delivers them at runtime with
# `pynq get-notebooks`, so /home/root/notebooks is empty at build time and that
# subpackage is never emitted. jupyter-startup already creates the dir.
IMAGE_INSTALL:append = " python3-pynq"

# Non-XRT device shim so Overlay/MMIO/allocate work on Zynq-7000 (no XRT).
IMAGE_INSTALL:append = " python3-zynq-cma-device"
